backend:
  name: github
  repo: JFabianGuillen/fabianguillen-blog
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - file: "index.html"
        label: "Inicio"
        name: "inicio"
        fields:
          - { label: "Cuerpo", name: "body", widget: "markdown" }
